name: sounds_codec
version: 1.0.2
homepage: https://github.com/bsutton/sounds_codec
documentation: https://github.com/bsutton/sounds_codec/wiki
description: An api to help do codec conversions. Design to work with the Sounds package but should be useable by any app needing codec conversions.
  This uses the ffmpeg library so it is fairly heavy weight (which is why it was removed from Sounds).
repository: https://github.com/bsutton/sounds_codec
environment: 
  sdk: '>=2.8.1 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
dependencies: 
  sounds_common: ^1.0.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  pedantic: ^1.9.0
  test: ^1.14.4
  effective_dart: ^1.2.1
